### ISSUE TITLE
NullPointerException, on Android OS 5.0 or 5.1

### ISSUE THREAD

**Issue by futabooo** [KazaKago/Cryptore#7]
Hi, thank you your nice library.
I try kotlin sample on Android OS 5.0 and 5.1. And I have problem.

```
java.lang.NullPointerException: context == null
    at android.security.KeyPairGeneratorSpec$Builder.<init>(KeyPairGeneratorSpec.java:355)
    at com.kazakago.cryptore.RSACryptore.createNewKey(RSACryptore.kt:63)
    at com.kazakago.cryptore.BaseCryptore.<init>(BaseCryptore.kt:27)
    at com.kazakago.cryptore.RSACryptore.<init>(RSACryptore.kt:26)
    at com.kazakago.cryptore.Cryptore$Builder.build(Cryptore.kt:83)
    at com.kazakago.cryptore.samplekotlin.MainActivity$cryptoreRSA$2.invoke(MainActivity.kt:25)
    at com.kazakago.cryptore.samplekotlin.MainActivity$cryptoreRSA$2.invoke(MainActivity.kt:13)
    at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
    at com.kazakago.cryptore.samplekotlin.MainActivity.getCryptoreRSA(MainActivity.kt)
    at com.kazakago.cryptore.samplekotlin.MainActivity.encryptRSA(MainActivity.kt:70)
    at com.kazakago.cryptore.samplekotlin.MainActivity.access$encryptRSA(MainActivity.kt:13)
    at com.kazakago.cryptore.samplekotlin.MainActivity$onCreate$1.onClick(MainActivity.kt:44)
    at android.view.View.performClick(View.java:4756)
    at android.view.View$PerformClick.run(View.java:19749)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by kazakago** [comment]
@futabooo Thank you your issue report!
I confirmed that my code crashes on API 21 and 22 and your PR code works correctly.

I merged your PR, thanks!
